import bcrypt from "bcrypt";
const data = {
  users: [
    {
      name: "Harkirat",
      email: "amh2harkirat@gmail.com",
      password: bcrypt.hashSync('12345', 10),
      isAdmin: true,
    },
    {
      name: "Reza",
      email: "reza@gmail.com",
      password: bcrypt.hashSync('12345', 10),
      isAdmin: false,
    },
  ],
  cars: [
    {
      make: "Toyota",
      model: "Camry",
      year: 2017,
      kilometers: 50000,
      price: 15000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Silver",
      location: "Vancouver",
      image1: "/car_images_used/camry2017_1.jpg",
      image2: "/car_images_used/camry2017_2.jpg",
      slug: "toyota-camry-2017-silver",
      vin: "1G1JC5447R7133025",
    },
    {
      make: "Honda",
      model: "Civic",
      year: 2018,
      kilometers: 40000,
      price: 13000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Black",
      location: "Surrey",
      image1: "/car_images_used/civic2018_1.jpg",
      image2: "/car_images_used/civic2018_2.jpg",
      slug: "honda-civic-2018-black",
      vin: "2C3CCAAG9GH129738",
    },
    {
      make: "Chevrolet",
      model: "Malibu",
      year: 2016,
      kilometers: 60000,
      price: 12000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Blue",
      location: "Burnaby",
      image1: "/car_images_used/malibu2016_1.jpg",
      image2: "/car_images_used/malibu2016_2.jpg",
      slug: "chevrolet-malibu-2016-blue",
      vin: "JN1BJ1CP7KW207194",
    },
    {
      make: "Ford",
      model: "Escape",
      year: 2015,
      kilometers: 80000,
      price: 10000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Red",
      location: "Coquitlam",
      image1: "/car_images_used/escape2015_1.jpg",
      image2: "/car_images_used/escape2015_2.jpg",
      slug: "ford-escape-2015-red",
      vin: "WBA3N3C52EK243150",
    },
    {
      make: "Nissan",
      model: "Rogue",
      year: 2017,
      kilometers: 55000,
      price: 14000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "White",
      location: "Richmond",
      image1: "/car_images_used/rogue2017_1.jpg",
      image2: "/car_images_used/rogue2017_2.jpg",
      slug: "nissan-rogue-2017-white",
      vin: "5NPDH4AE5EH503773",
    },
    {
      make: "Hyundai",
      model: "Tucson",
      year: 2016,
      kilometers: 70000,
      price: 11000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Grey",
      location: "Langley",
      image1: "/car_images_used/tuscon2016_1.jpg",
      image2: "/car_images_used/tuscon2016_2.jpg",
      slug: "hyundai-tucson-2016-grey",
      vin: "KM8J33A27JU635090",
    },
    {
      make: "Kia",
      model: "Sorento",
      year: 2015,
      kilometers: 75000,
      price: 13000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Black",
      location: "Victoria",
      image1: "/car_images_used/sorento2015_1.jpg",
      image2: "/car_images_used/sorento2015_2.jpg",
      slug: "kia-sorento-2015-black",
      vin: "1HGCR2F30EA167087",
    },
  ],
};

export default data;
