const data = {
  cars: [
    {
      make: "Honda",
      model: "Accord",
      year: 2017,
      kilometers: 50000,
      price: 18000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "White",
      location: "Vancouver, BC",
      image: "https://example.com/images/1.jpg",
    },
    {
      make: "Toyota",
      model: "Corolla",
      year: 2015,
      kilometers: 75000,
      price: 12000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Silver",
      location: "Richmond, BC",
      image: "https://example.com/images/2.jpg",
    },
    {
      make: "Ford",
      model: "Escape",
      year: 2018,
      kilometers: 40000,
      price: 22000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Blue",
      location: "Surrey, BC",
      image: "https://example.com/images/3.jpg",
    },
    {
      make: "Nissan",
      model: "Altima",
      year: 2016,
      kilometers: 60000,
      price: 15000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Black",
      location: "Burnaby, BC",
      image: "https://example.com/images/4.jpg",
    },
    {
      make: "Chevrolet",
      model: "Cruze",
      year: 2017,
      kilometers: 55000,
      price: 13000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Red",
      location: "Langley, BC",
      image: "https://example.com/images/5.jpg",
    },
    {
      make: "Mazda",
      model: "CX-5",
      year: 2019,
      kilometers: 25000,
      price: 28000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Grey",
      location: "Victoria, BC",
      image: "https://example.com/images/6.jpg",
    },
    {
      make: "Hyundai",
      model: "Tucson",
      year: 2016,
      kilometers: 70000,
      price: 16000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "Silver",
      location: "Coquitlam, BC",
      image: "https://example.com/images/7.jpg",
    },
    {
      make: "Kia",
      model: "Sportage",
      year: 2015,
      kilometers: 80000,
      price: 14000,
      condition: "Used",
      fuel_type: "Gasoline",
      color: "White",
      location: "Nanaimo, BC",
      image: "https://example.com/images/8.jpg",
    },
  ],
};

export default data;
